---
title: "tolerance curves plotting"
author: "Silas Tittes"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document: default
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
---

```{r setup}
knitr::opts_knit$set(
  root.dir = '~/Documents/Projects/tolerance-curve2/'
  )
```

sim_params3
  ## Data prep
```{r}
source("load_data.R")
draws <- read_csv("bayes/stan_par1_df.csv") #draws for penalized zero model
draw_fits <- read_csv("bayes/fitted_points_mod1.csv")
```

## Trace plots and stan summary
```{r}
#note parameters as discussed in paper are:
  #a = alpha
  #b = beta
  #c = zeta
  #d = delta
  #e1 = epsilon
#traceplot for parameter for each species

stan_sum <- summary(stanDat, par = c("a", "b", "c", "d", "e", 
                                     "beta_0", "beta_1", "nu"))$summary

options(xtable.sanitize.colnames.function=identity,
          xtable.sanitize.rownames.function=identity)
print.xtable(
  xtable(round(stan_sum, 2)), comment = F, file = "stan_table.tex",
  tabular.environment='longtable', include.colnames = TRUE,
  floating=FALSE, add.to.row = list(pos = list(0), command = "\\hline \\endhead "))

pdf("figures/trace_a.pdf")
rstan::traceplot(stanDat, par=c("a"))
dev.off()

pdf("figures/trace_b.pdf")
rstan::traceplot(stanDat, par=c("b"))
dev.off()

pdf("figures/trace_c.pdf")
rstan::traceplot(stanDat, par=c("c"))
dev.off()

pdf("figures/trace_d.pdf")
rstan::traceplot(stanDat, par=c("d"))
dev.off()

pdf("figures/trace_e.pdf")
rstan::traceplot(stanDat, par=c("e"))
dev.off()

pdf("figures/trace_beta_0.pdf")
rstan::traceplot(stanDat, par=c("beta_0"))
dev.off()

pdf("figures/trace_beta_1.pdf")
rstan::traceplot(stanDat, par=c("beta_1"))
dev.off()

pdf("figures/trace_nu.pdf")
rstan::traceplot(stanDat, par=c("nu"))
dev.off()

```


## Raw parameter prob differences
```{r}

comp_matrices <- function(var, cut = 0.95){
  
  #high <- 1 - (1 - cut)/2
  #low <- (1 - cut)/2
  high <- cut
  low <- 1 - cut

  #var <- post_params[1]
  var_df <- draws %>%
    select(Species, draw, one_of(var)) %>%
    rename_(var = var) %>%
    spread(key = Species, value = var) %>%
    select(-draw)
  
  map_comp_p <- map_df(var_df, ~{
    map_dbl(var_df, function(x){
      comp_p <- mean(.x > x)
      ifelse(comp_p > high | comp_p < low, round(mean(.x - x), 1), NA)
    })
  }) %>% as.matrix
  
  map_comp_p[upper.tri(map_comp_p, diag = T)] <- NA
  map_comp_p <- cbind(colnames(map_comp_p), map_comp_p)
  colnames(map_comp_p) <- paste0(substr(colnames(map_comp_p), 1, 2), ".")
  colnames(map_comp_p)[1] <- tab_strings[which(post_params == var)]
  
  write.csv(map_comp_p, 
            file = paste0("derived_files/parameter_comp_matrices/", var,"_matrix.csv"))
  
  options(xtable.sanitize.colnames.function=identity,
          xtable.sanitize.rownames.function=identity)
  
  #print.xtable(xtable(map_comp_p), size="\\fontsize{5pt}{5pt}\\selectfont", 
  #             file = pair_file, append = TRUE, include.rownames=FALSE)
  print.xtable(xtable(map_comp_p), 
               file = pair_file, append = TRUE, include.rownames=FALSE)
  
  
}


post_params <- c("d", "maxima", "e", "c", "breadth", "area")
tab_strings <- c("$\\delta$", "optima", "$\\epsilon$", "$\\zeta$", "$\\epsilon - \\delta$", "area")
names(post_params) <- tab_strings 
pair_file <- "derived_files/parameter_comp_matrices/post_all_comparisons.tex"
file.create(pair_file)
post_params %>% map( ~ comp_matrices(var = .x)) %>% invisible

```




## Plotting phylogenetic signal of curves
```{r}
sig <- read_csv("derived_files/curve_K.csv")

sig %>% group_by(param) %>%
  summarise(quant = quantile(signal, probs = 0.975)) %>%
  arrange(quant) 

#sig_den <- sig %>% group_by(param) %>%
#  do(den = density(sig$signal))

cairo_pdf("figures/fig4.pdf")
#png(filename = "figures/signal.png")
sig %>%
  mutate(param = sub("maxima", "optima", param)) %>%
  filter(!param %in% c("special", "area")) %>%
  mutate(param = str_replace_all(param, 
                c("^c$" = "ζ", 
                  "^d$" = "δ", 
                  "^e$" = "ε")
                )) %>% 
  ggplot(aes(x = signal)) +
  geom_density(fill="blue", alpha = 0.8) +
  facet_wrap(~param, ncol = 2) +
  theme_classic() +
  theme(text = element_text(size=16))
dev.off()

```



## Parameter density plot with phylogeny version 2
```{r}

plot_concept <- function(){
  #conceptual plot over top of densities
  off <- 0.2
  a <- 4
  b <- 2.7
  c <- 5.5
  d <- 0
  e <- 1
  xseq_0 <- seq(0,1, length.out = 500)
  xseq_a <- xseq_0 * (e - d) + d
  fa = stretch_kumara(x = xseq_0, a, b, c)
  opt_loc <- (((a - 1)/(a*b - 1))^(1/a) * (e - d) + d)
  low_loc <- d
  high_loc <- e
  bredth <- e - d
  
  arr_len <- 0.05
  par_cex <- 1.4
  
  plot(xseq_a, fa, type = "l", lwd = 4, axes = F, xlab = "", ylab = "",
       ylim = c(0, max(fa)*1.25) )
  axis(1, labels = F); axis(2, labels = F)
  mtext(text = "Fitness", side = 2, line = 1.2)
  mtext(text = "Environment", side = 1, line = 1.2)
  
  #polygon for area
  polygon(x = c(rev(xseq_a), xseq_a), y = c(rep(0, length(fa)), fa), 
          density = 100, col = alpha("black", 0.05), border = T, lwd = 2)
  text(0.7, mean(fa), "Area")
  
  text(x = opt_loc, y = max(fa)*(1-off), "maxima")
  points(x = opt_loc, y = max(fa), pch = 21, bg = "white", cex = 1.2)
  
  
  text(x = low_loc, y = max(fa)*off, expression(delta), cex = par_cex)
  points(x = low_loc, y = 0, pch = 21, bg = "white", cex = 1.2)
  
  text(x = high_loc, y = max(fa)*off, expression(epsilon), cex = par_cex)
  points(x = high_loc, y = 0, pch = 21, bg = "white", cex = 1.2)
  
  #segment for zeta
  #calc kums with zeta = 1
  z1 <- max(stretch_kumara(x = xseq_0, a, b, 1))
  za <- max(fa)
  zeta_loc <- low_loc + 0.25
  arrows(x0 = zeta_loc, y0 = za, x1 = zeta_loc, y1 = z1, 
         code = 3, angle = 90, length = arr_len, lwd = 2, col = "grey50")
  text(x = zeta_loc + 0.02, y = (z1+za)/2, expression(zeta), cex = par_cex)

  
  yy <- 4
  arrows(x0 = 0, y0 = max(fa)+1, x1 = high_loc, y1 = max(fa)+1, 
         code = 3, angle = 90, length = arr_len, lwd = 2, col = "grey50")
  
  text(x = median(xseq_a), y = max(fa)+2.5, expression(epsilon - delta), cex = par_cex)
  
}

source("derived_files/state_reg.R")
#set habitat colors
colz <- topo.colors(n = 12, alpha = 0.7)[c(11,4)]
colz2 <- topo.colors(n = 12, alpha = 1)[c(11,4)]
names(colz) <- c("terrestrial","vernal")
colz_par <- colz[match(state_reg_aqua_terr2terr, names(colz))]
names(colz_par) <- names(state_reg_aqua_terr2terr)


spp_list <- rev(lasth$tip.label[lasth$edge[,2][lasth$edge[,2] <= length(lasth$tip.label)]])

pdf("figures/fig3.pdf")
#png(filename = "figures/fig4_curves.png")

cnc <- 1
ml <- rbind(c(0, 0, 0, 0, 0, 0),
            c(0, 1, 1, 1, 0, 0),
            c(0, 1, 1, 1, 0, 0),
            c(0, 1, 1, 1, 0, 0),
            cbind(rep(2,length(spp_list)),
            matrix(seq_along(spp_list)+1+cnc), 
            matrix(seq_along(spp_list)+length(spp_list)+1+cnc),
            matrix(seq_along(spp_list)+2*length(spp_list)+1+cnc),
            matrix(seq_along(spp_list)+3*length(spp_list)+1+cnc),
            matrix(seq_along(spp_list)+4*length(spp_list)+1+cnc)),
            rep(0, 6), rep(0, 6))

layout(ml)

par(mar = c(2,2,0,0))
plot_concept()
par(mar = c(0,0,0,0))

plot.phylo(lasth, edge.width = 2, show.tip.label = F)

post_params <- c("d", "maxima", "e", "c")
greek_params <- c(expression(delta), expression(optima), expression(epsilon), expression(zeta))


seq_along(post_params) %>% map(function(x){
  var <- post_params[x]
den_var <- draws %>% 
  group_by(Species) %>%
  do(den = density(.[[var]]))

den_range <- den_var$den %>% map_df(~{
  xl = quantile(.x$x, 0) 
  xh = quantile(.x$x, 1)
  yl = 0
  yh = quantile(.x$y, 1)
  cbind(xl, xh, yl, yh) %>% as_data_frame
}) %>% summarise_all(funs(min, max))


names(den_var$den) <- den_var$Species
seq_along(spp_list) %>% map(~{
 spp_den <- den_var$den[[spp_list[.x]]] 
 plot(spp_den$x, spp_den$y,
      xlim = c(den_range$xl_min, den_range$xh_max),
      ylim = c(0, den_range$yh_max),
      axes = F, type = "n")
 polygon(spp_den$x, spp_den$y, col = colz_par[spp_list[.x]], border  = T)
 if(var == "d") legend("left", spp_list[.x], bty = "n", cex = 0.8)
 })
axis(1)
mtext(greek_params[x], side = 1, line = 3)
}) %>% invisible


select <- dplyr::select
rename <- dplyr::rename
gradient <- read.xls("data/Pool depths_FINAL summary_REVISED.xls", 
                     header = T, skip = 1, stringsAsFactors = F) %>%
  mutate(taxa = strsplit(X, "_") %>% map_chr(~ .x[length(.x)]),
         taxa = ifelse(taxa == "deblilis", "debilis", taxa)) %>% 
  filter(taxa %in% as.character(unique(emery$Species)))


limz <- gradient %>%
  rowwise() %>%
  summarise(high = Mean + SE,
            low = Mean - SE) %>%
  summarise(maxy = max(high, na.rm = T)*1.1,
            miny = min(low, na.rm = T)*1.1)

spp_list %>%
  map(~{
    row_i <- gradient %>% filter(taxa == .x)
    par(mar = c(0,0,0,2))
    plot(
      NA, NA, 
      ylim =c(-0.1, 0.5),
      xlim = c(limz$miny, -limz$miny),
      axes = F, bty = "n")
    segments(
      y0 = 0,
      y1 = 0,
      x0 = row_i$Mean - row_i$SE, 
      x1 = row_i$Mean + row_i$SE,
      lwd = 1
      )
    points(row_i$Mean, 0, pch = 19)
    abline(v = 0, lty = 2)
    #text(0.3, limz$maxy, row_i$taxa)
    if(.x == spp_list[length(spp_list)]){
      axis(1, cex.axis = 0.85, 
           at = round(seq(limz$miny, -limz$miny, length.out = 4),2),
           labels = round(seq(limz$miny*100, -limz$miny*100, length.out = 4),0))
      mtext(side = 1, "depth (cm)", line = 3, cex = 0.85)              
      }
  })

dev.off()


```






## curve plots
```{r}

holo <- c("ferrisiae", "glabrata", "coulteri", "chrysantha")
emery_zeros <- read.xls("data/Inundation_compiled_FINAL.xlsx") %>%
  mutate(Inflor_biomass = ifelse(
    is.na(Inflor_biomass) &
      ifEmerge.Y.N. == 1, yes =  0,
    no = Inflor_biomass)) %>%
  mutate(
    treat = ifelse(
      Treatment == "F", yes = 5, 
      no = ifelse(
        Treatment == "MF", yes = 4, 
        no = ifelse(
          Treatment == "B", yes = 3, 
          no = ifelse(
            Treatment == "MD", yes = 2, 
            no = 1
          )
        )
      )
    )
  ) %>%
  filter(!is.na(Inflor_biomass)) %>%
  group_by(Species) %>%
  mutate(sppint = as.integer(Species)) %>% 
  group_by(Species, treat) %>%
  filter(sum(Inflor_biomass > 0) == 0) %>%
  ungroup() %>%
  mutate(
    Species_h = ifelse(
      as.character(Species) %in% holo, 
      "hologymne", as.character(Species)
    ), 
    sppint_h = as.integer(as.factor(Species_h))
  ) 


mean_draws <- draws %>% group_by(Species) %>%
  summarise(a = mean(a),
            b = mean(b),
            c = mean(c),
            d = mean(d),
            e = mean(e), 
            draw = 1)


#colz <- topo.colors(n = 12, alpha = 1)[c(11,4)]

#source("derived_files/state_reg.R")
#set habitat colors
source("derived_files/state_reg.R")
colz <- topo.colors(n = 12, alpha = 1)[c(11,4)]
colz2 <- topo.colors(n = 12, alpha = 1)[c(11,4)]
names(colz) <- c("terrestrial","vernal")
colz_par <- colz[match(state_reg_aqua_terr2terr, names(colz))]
names(colz_par) <- names(state_reg_aqua_terr2terr)

sppMaxVal <- by(data = emery$Inflor_biomass, 
                INDICES = emery$sppint, FUN = max)
names(sppMaxVal) <- unique(emery$Species)


#from liam revell's blog
simmap_prop <-function(x){
  y<-sapply(x$maps,function(x) names(x)[1])
  names(y)<-x$edge[,1]
  y<-y[as.character(length(x$tip)+1:x$Nnode)]
  return(y)
}


#get colors mapped to habitats for OUwie
#states <- colnames(reg_fit[[1]]$mapped.edge)
#names(states) <- colz
#colz <- names(states)
#names(colz) <- states


#habz <- colnames(reg_fit[[1]]$mapped.edge)
#sim_states <- sapply(reg_fit, simmap_prop)
#pies_sim <-t(apply(sim_states,1,
#               function(x,levels,Nsim){
#                 summary(factor(x,levels))/Nsim},
#               levels=habz, Nsim=ncol(sim_states)))



#plot data
spp_list <- rev(lasth$tip.label[lasth$edge[,2][lasth$edge[,2] <= length(lasth$tip.label)]])
cut <- 0.99
lo <- (1 - cut)/2
hi <- 1 - (1 - cut)/2
xrng <- draw_fits$x %>% quantile(c(lo, hi))
yrng <- max(emery$Inflor_biomass)


#pdf(paste0(getwd(),"/figures/tree_tolerance.pdf"))
#png(filename = "figures/fig3_tree_tolerance.png") #alt
pdf("figures/fig2.pdf") #alt
#svg("figures/fig3_tree_tolerance.svg") #alt

c1 <- rep(1, length(spp_list))
c_2_4 <- rep(0, length(spp_list))
c3 <- 2:(length(spp_list)+1)
m_lay <- cbind(c1, c1, c1, c3, c3, c_2_4)
m_lay <- rbind(rep(0, ncol(m_lay)), m_lay, rep(0, ncol(m_lay)))
layout(m_lay, 
       widths = c(0.25, 0.25, 0.25, 0.2, 0.2, 0.05), 
       heights = c(0.01, rep(1/(nrow(m_lay)-2), (nrow(m_lay)-2)), 0.05) )

par(mar=c(0,0,0,0))

plot.phylo(lasth, show.tip.label = F, edge.width = 4, 
           no.margin = T)
#nodelabels(pie=pies_sim, piecol=colz, cex = 1.2)
tiplabels(pch = 22, cex = 3,
          bg = colz[state_reg_aqua_terr2terr[lasth$tip.label]])

#format node support for labeling
node_fmt <- ifelse(lasth$node.label < 1, 
                   substring(sprintf("%4.2f", lasth$node.label), 2),
                   lasth$node.label)

nodelabels(node_fmt, frame = "n", 
           cex = 1, font = 2, pos=4, offset = 1)


legend("bottomleft", c("Terrestrial", "Vernal pool"), pch = 22, pt.cex = 1.5,
       pt.bg = colz, cex = 1.2, bg = "white")


for(spp in spp_list){
  
  #spp <- spp_list[14]
  #plt_draws <- 500 #!!!!
  n_draws <- posts$lp__ %>% nrow
  spp_draws <- draw_fits %>% filter(draw <= n_draws, Species == spp)
  
  par(mar=c(0,2,0,0))  
  plot(
    NA, NA,
    ylim = c(0, yrng), xlim = xrng,
    axes=F, xlab="", ylab=""
  )
  box()
  
  1:n_draws %>% map(~ {
    c_draw <- spp_draws %>% filter(draw == .x)
    lines(c_draw$x, c_draw$y,
          col=alpha(colour = "black", alpha = 0.1))
  })


  spp_mean <- mean_draws %>% filter(Species == spp)
  mean_line <- plot_kumara(xs = seq(0, 1, length.out = 100),
               a = spp_mean$a, spp_mean$b, spp_mean$c, spp_mean$d, e=spp_mean$e)

  lines(mean_line[[1]], mean_line[[2]], 
        lwd = 1.5, col = colz[state_reg_aqua_terr2terr[spp]])
      
  
  
  subEm <- emery %>% filter(Species == spp)
  subEm_0 <- emery_zeros %>% filter(Species == spp)
  
  points( jitter(subEm$treat, factor = 0.2), subEm$Inflor_biomass, 
           pch=19, col=alpha("grey70", 0.75))
  
  points( jitter(subEm_0$treat, factor = 0.2), subEm_0$Inflor_biomass, 
           pch=19, col=alpha("blue", 0.25))
  
    
  legend("topleft", spp, bty="n", text.font = 3)
  
}


axis(side = 2, cex.axis = 0.85, at = round(yrng), las = 1)
axis(side = 1, cex.axis = 0.85)

dev.off()

```


Plotting observed versus predicted
```{r}

meanDraws <- apply(X = posts$mu, 2, mean)

predDF <- data.frame(meanDraws = meanDraws,
                     Inflor_biomass = emery$Inflor_biomass)
predDF_nZero <- predDF[predDF$Inflor_biomass != 0, ]
predDF_Zero <- predDF[predDF$Inflor_biomass == 0, ]

#plot(emery$Inflor_biomass, meanDraws)
#abline(0,1, lty=2, col="red")

pdf("figures/figB11.pdf")
plot(predDF_nZero$meanDraws, (predDF_nZero$Inflor_biomass - predDF_nZero$meanDraws),
     pch=as.integer(emery$Species), xlab = "fitted values", ylab = "residuals")

points(
  predDF_Zero$meanDraws, 
  (predDF_Zero$Inflor_biomass - predDF_Zero$meanDraws),
  pch="z", cex=1.5
  )

smth <- smooth.spline(predDF_nZero$meanDraws, 
                      predDF_nZero$Inflor_biomass - predDF_nZero$meanDraws)
abline(h=0, lty = 2)
lines(smth$x, smth$y, lty=3, lwd = 2)

legend("topleft", c(as.character(unique(emery$Species))),
       pch = unique(as.integer(emery$Species)), 
       ncol = 2, cex =0.4)
dev.off()

```


## Plotting parameter densities with priors
```{r, eval = TRUE}

spp_names <- emery %>% select(Species, sppint) %>% 
  unique() %>% 
  arrange(sppint)

par <- c("a", "b", "c", "d", "e")
spp_par <- c(paste0(par, "_t"), "beta_0", "beta_1", "nu")
hier_par <- paste0("mean_", c(par, "beta_0", "beta_1", "nu"))
param_letters <- c("α", "β", "ζ", "δ", "ε", "β_0", "β_1", "ν") %>% as_tibble

plt_params <- function(p, den_rng, pr_mu, pr_sd){
  posts[[spp_par[p]]] %>%
    as.data.frame() %>%
    set_colnames(spp_names$Species) %>%
    gather(species, val) %>%
    ggplot() +
    geom_area( stat = "function", 
              fun = dnorm,  
              args = list(mean = pr_mu, sd = pr_sd), 
              fill = "red", 
              alpha = 0.5,
              colour="black",
              xlim = den_rng) +
    geom_density( data = as_tibble(posts[[hier_par[p]]]), 
                  mapping = aes(x = value), 
                  fill = "dodgerblue",
                  alpha = 0.5) +
    geom_density(aes(x = val, color = species), lwd = 0.75, alpha = 0.25) +
    ggtitle(param_letters$value[p]) +
    theme_minimal() +
    theme(plot.title = element_text(hjust = 0.5))
}

cairo_pdf(filename = paste0("figures/B", 3, ".pdf"))
plt_params(p = 1, den_rng = c(-6,6), -1, 1)
dev.off()

cairo_pdf(filename = paste0("figures/B", 4, ".pdf"))
plt_params(p = 2, den_rng = c(-6,6), -1, 1)
dev.off()

cairo_pdf(filename = paste0("figures/B", 5, ".pdf"))
plt_params(p = 3, den_rng = c(-3,3), 0, 1) 
dev.off()

cairo_pdf(filename = paste0("figures/B", 6, ".pdf"))
plt_params(p = 4, den_rng = c(-3,3), 0, 1) 
dev.off()

cairo_pdf(filename = paste0("figures/B", 7, ".pdf"))
plt_params(p = 5, den_rng = c(-3,3), 0, 1) 
dev.off()

cairo_pdf(filename = paste0("figures/B", 8, ".pdf"))
plt_params(p = 6, den_rng = c(-3,3), 0, 1) 
dev.off()

cairo_pdf(filename = paste0("figures/B", 9, ".pdf"))
plt_params(p = 7, den_rng = c(-3,3), 0, 1) 
dev.off()

cairo_pdf(filename = paste0("figures/B", 10, ".pdf"))
plt_params(p = 8, den_rng = c(-3,3), 2, 1) #+ theme(legend.position="none")
dev.off()

```


