---
title: "tolerance curve plots"
author: "Silas Tittes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
---

```{r, echo=FALSE, results='hide', message=FALSE}
#packages
library(rmarkdown)
library(knitr)
library(formatR)
library(xtable)
library(dplyr)
library(ggplot2)
library(smoothmest)
library(rstan)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

#options(scipen=99) #avoid scientific notation when printing
opts_chunk$set(tidy=TRUE, tidy.opts=list(width.cutoff=70, message=FALSE, results='hide'))
options(bitmapType="cairo")

HDI <- function(values, percent=0.95){
  sorted <- sort(values)
  index <- floor(percent * length(sorted))
  nCI <- length(sorted) - index
  width <- rep(0, nCI)
  for (i in 1:nCI){
    width[i] <- sorted[i + index] - sorted[i]
  }
  HDImin <- sorted[which.min(width)]
  HDImax <- sorted[which.min(width) + index]
  HDIlim <- c(HDImin, HDImax)
  return(HDIlim)
}


stretch.kumara <- function(x, a, b, c){
  return(c*((a*b*x^(a-1) ) * (1-x^a)^(b-1)))
}


opar <- par()
opar$cin <- NULL
opar$cra <- NULL
opar$csi <- NULL
opar$cxy <- NULL
opar$din <- NULL
opar$page <- NULL
```


```{r, echo=FALSE, results='hide', message=FALSE}
setwd("~/Documents/Projects/toleranceCurves/bayes/")
emery <- read.csv("NEmeryData.csv", header=T)
emery <- emery[is.na(emery$Inflor_biomass) == 0,]

###DELETE THIS###
#emery <- emery[emery$Inflor_biomass != 0,]

emery$treat <- rep(NA, nrow(emery))

#make new column with treatments quant instead of nominal
for(i in 1:nrow(emery)){
  if( emery$Treatment[i] == "F"){
    emery$treat[i]  <- 5
  } else if(emery$Treatment[i] == "MF"){
    emery$treat[i]  <- 4
  } else if(emery$Treatment[i] == "B"){
    emery$treat[i]  <- 3
  } else if (emery$Treatment[i] == "MD"){
    emery$treat[i]  <- 2
  } else if (emery$Treatment[i] == "D"){
    emery$treat[i]  <- 1
  } else {
    emery$treat[i]  <- NA
  }
}

#make another new column with species as integers instead of nominal for stan
species <- unique(emery$Species)
sppint <- 1:length(species)
emery$sppint <- rep(NA, nrow(emery))
for(i in 1:length(species)){
  emery$sppint[emery$Species %in% species[i]]  <- sppint[i]
}


dataList <- list(N = nrow(emery), 
		 x = emery$treat, 
		 y = emery$Inflor_biomass,
		 numSpp = length(unique(emery$sppint)),
		 sppint = emery$sppint
		)

```



##Predicting tolerance curves from vernal pool community data
```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE, error=FALSE}
library(ggplot2)
ggplot(emery, aes(x=treat, y=Inflor_biomass)) +
  geom_point() +
  stat_smooth(method = "loess") +
  facet_wrap(~ Species) +
  labs(x="Moisture Treatment",y="Floral Biomass") +
  theme_light()
```



```{r, echo=FALSE, results='hide', message=FALSE}
stan_samples <- list.files()[(grep ("tolerance_zig.samples", list.files()))]
stan_stats <- list.files()[(grep ("tolerance_zig.diag", list.files()))]
stanDat <- rstan::read_stan_csv(stan_samples)
stanMod <- rstan::read_stan_csv(stan_stats)
posts <- rstan::extract(stanDat)
ndraws <- nrow(posts$lp__)
summs <- summary(stanMod)$summary
```



## Posterior and prior densities
```{r, echo=FALSE, results='hide', message=FALSE}

library(truncnorm)

par(mfrow=c(3,2))
par(mar=c(3,3,1,1))

denA_pr <- density(rtruncnorm(n = ndraws, mean = 2, sd = 2, a = 2) )
denA <- density(posts$hyper_a)
plot(denA$x, denA$y, xlim=range(posts$a), ylim=c(0,0.75),type="n")
polygon(denA_pr, col=alpha("red",0.5))
polygon(denA, col=alpha("dodgerblue",0.5))
for(i in 1:dataList$numSpp){
  cDenA <- density(posts$a[,i])
  lines(cDenA$x, cDenA$y)
}
legend("topright", "a", bty="n", cex=2)

denB_pr <- density( rtruncnorm(n = ndraws, mean = 2, sd = 2, a = 2) )
denB <- density(posts$hyper_b)
plot(denB$x, denB$y, xlim=range(posts$b), type="n", ylim=c(0,0.9))
polygon(denB_pr, col=alpha("red",0.5))
polygon(denB, col=alpha("dodgerblue",0.5))
for(i in 1:dataList$numSpp){
  cDenB <- density(posts$b[,i])
  lines(cDenB$x, cDenB$y)
}
legend("topright", "b", bty="n", cex=2)


denC_pr <- density( rtruncnorm(n = ndraws, mean = 1, sd = 2, a = 1) )
denC <- density(posts$hyper_c)
plot(denC$x, denC$y, xlim=range(posts$c), type="n", ylim=c(0,1.4))
polygon(denB, col=alpha("red",0.5))
polygon(denC, col=alpha("dodgerblue",0.5))
for(i in 1:dataList$numSpp){
  cDenC <- density(posts$c[,i])
  lines(cDenC$x, cDenC$y)
}
legend("topright", "c", bty="n", cex=2)

denD_pr <- density( rtruncnorm(n = ndraws, mean = min(emery$treat), sd = 2, b = min(emery$treat)) )
denD <- density(posts$hyper_d)
plot(denD$x, denD$y, xlim=range(posts$d), type="n", ylim=c(0,0.45))
polygon(denD_pr, col=alpha("red",0.5))
polygon(denD, col=alpha("dodgerblue",0.5))
for(i in 1:dataList$numSpp){
  cDenD <- density(posts$d[,i])
  lines(cDenD$x, cDenD$y)
}
legend("topleft", "d", bty="n", cex=2)

denE_pr <- density( rtruncnorm(n = ndraws, mean = max(emery$treat), sd = 2, a = max(emery$treat)) )
denE <- density(posts$hyper_e)
plot(denC$x, denC$y, xlim=range(posts$e1), type="n", ylim=c(0,0.4))
polygon(denE_pr, col=alpha("red",0.5))
polygon(denE, col=alpha("dodgerblue",0.5))
for(i in 1:dataList$numSpp){
  cDenC <- density(posts$e[,i])
  lines(cDenC$x, cDenC$y)
  cDenC <- density(posts$e1[,i])
  lines(cDenC$x, cDenC$y, col="blue")
}
legend("topright", "e", bty="n", cex=2)

par(opar)

```





## Y = Floral Biomass, X = Moisture Treatment
```{r, echo=FALSE, results='hide', message=FALSE}
xseq <- seq(0,1, length.out=500)


par(mfrow=c(3,3))
par(mar=c(3,3,1,1))
#

#xlow <- min(posts$d)
#xhigh <- max(posts$e1+posts$d)
#yrng <- c(0, max(emery$Inflor_biomass))
  
  for(j in 1:7){
    
    emery_sub <- subset(emery, sppint == j)
    
    cSpp <- as.character(unique(emery_sub$Species))
    #plot( jitter(emery$treat), emery$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    #plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    
    xlow <- mean(posts$d[,j])
    xhigh <- mean(posts$e1[,j]+posts$d[,j])
    
    #pdf(file = paste0("figures/",cSpp,".pdf"))
    #png(filename = paste0("figures/",cSpp,".png"))
    
    plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, type="n", xlim=c(xlow, xhigh),
          ylab="Floral Biomass", xlab="Moisture Treatment")
  
    for(i in 1:ndraws){
    mod.fit <- stretch.kumara(x = xseq, a= posts$a[i,j],# + posts$hyper_a[i],
                              b = posts$b[i,j],# + posts$hyper_b[i],
                              c = posts$c[i,j] # + posts$hyper_c[i]
                              )
      lines(xseq*posts$e1[i,j] + posts$d[i,j], mod.fit, lwd=1, col=alpha("dodgerblue", 0.05))
    }
  
    points( jitter(emery_sub$treat), emery_sub$Inflor_biomass, pch=19, col=alpha("grey10", 0.8))
    spln <- smooth.spline(emery_sub$treat, emery_sub$Inflor_biomass)
    lines(spln$x, spln$y, lwd=2, col=alpha("red",0.9))
    legend("topleft", cSpp, bty="n", cex=1.1)
    
    #dev.off()
  }

par(opar)

```



## Y = Floral Biomass, X = Moisture Treatment
```{r, echo=FALSE, results='hide', message=FALSE}
xseq <- seq(0,1, length.out=500)


par(mfrow=c(3,3))
par(mar=c(3,3,1,1))
#

#xlow <- min(posts$d)
#xhigh <- max(posts$e1+posts$d)
#yrng <- c(0, max(emery$Inflor_biomass))
  
  for(j in 8:max(emery$sppint)){
    
    emery_sub <- subset(emery, sppint == j)
    
    cSpp <- as.character(unique(emery_sub$Species))
    #plot( jitter(emery$treat), emery$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    #plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    
    xlow <- mean(posts$d[,j])
    xhigh <- mean(posts$e1[,j]+posts$d[,j])
    
    #pdf(file = paste0("figures/",cSpp,".pdf"))
    #png(filename = paste0("figures/",cSpp,".png"))
    
    plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, type="n", xlim=c(xlow, xhigh),
          ylab="Floral Biomass", xlab="Moisture Treatment")
  
    for(i in 1:ndraws){
    mod.fit <- stretch.kumara(x = xseq, a= posts$a[i,j],# + posts$hyper_a[i],
                              b = posts$b[i,j],# + posts$hyper_b[i],
                              c = posts$c[i,j] # + posts$hyper_c[i]
                              )
    
      mod.fit.zig <- mod.fit * 
        (1 - plogis(posts$beta_0[i] + posts$beta_1[i] * mod.fit))
      xdat <- xseq*posts$e1[i,j] + posts$d[i,j]
      lines(xdat, mod.fit.zig, lwd=1, col=alpha("dodgerblue", 0.5))
      
    #ydat1 <- stretch.kumara(xseq, post$a[i,j], post$b[i,j], post$c[i,j])
    #yzig <- ydat1 * (1 - plogis(post$beta_0[i] + post$beta_1[i] * ydat1))
    #lines(xdat1, ydat1)
    #lines(xdat1,yzig, col=j)
      
    }
  
    points( jitter(emery_sub$treat),
            emery_sub$Inflor_biomass, pch=19,
            col=alpha("grey10", 0.8))
    
    spln <- smooth.spline(emery_sub$treat, emery_sub$Inflor_biomass)
    
    lines(spln$x, spln$y, 
          lwd=2, col=alpha("red",0.9)
          )
    
    legend("topleft", cSpp, bty="n", cex=1.1)
    
    #dev.off()
  }

par(opar)

```



##Predictions, (check out dem zeros!)
```{r, echo=FALSE, results='hide', message=FALSE}
muHDI <- apply(posts$mu, 2, HDI)
muMean <- apply(posts$mu, 2, mean)
meanbeta0 <- mean(posts$beta_0)
meanbeta1 <- mean(posts$beta_1)

muZig <- ifelse(emery$Inflor_biomass != 0, 
       (1 - plogis(meanbeta0 + meanbeta1 * muMean)) * muMean, 
        plogis(meanbeta0 + meanbeta1 * muMean))


plot(emery$Inflor_biomass, 
     muZig, type="n",
     ylim=range(muHDI),
     xlab="Observed",
     ylab="Predicted")

#does not account for zig
#segments(x0 = emery$Inflor_biomass, 
#         y0 = muHDI[,1], 
#         x1 = emery$Inflor_biomass, 
#         y1 = muHDI[2,], 
#         col=alpha("dodgerblue", 0.5), 
#         lwd=2)

points(emery$Inflor_biomass, muZig, pch=19, col="grey20")
abline(0,1)
```



##A Zero by any other name ...
```{r, echo=FALSE, results='hide', message=FALSE}
# add line for every draw
jitmu <- jitter(as.numeric(emery$Inflor_biomass < 1), 
                factor = 0.4)

plot(muHDI[1,],
     jitmu,
     type="n",
     xlim=c(min(muHDI[1,]),
            max(muHDI[2,])),
     xlab=expression(mu),
     ylab="Probability(y=0)"
     )


mu_vals <- seq(min(emery$Inflor_biomass),
               max(emery$Inflor_biomass),
               length.out = 1000)


segments(x0 = muHDI[1,],
         y0 = jitmu,
         x1 = muHDI[2,],
         y1 =jitmu,
         col=alpha("blue", 0.5)
         )

#plot(x = NULL, y = NULL, xlim = range(emery$Inflor_biomass), ylim = c(0, 1),
#     xlab = "mu", ylab = 'Pr(zero)')

for (i in 1:ndraws) {
  lines(mu_vals, 
        plogis(posts$beta_0[i] + posts$beta_1[i] * mu_vals))
}


#psegments(x0 = muHDI[1,], y0 = jitmu, x1 = muHDI[2,], y1 =jitmu, lty=2, col=alpha("blue", 0.8) )
#plot(muHDI[1,], as.numeric(emery$Inflor_biomass < 1))
#zigglm <- glm( as.numeric(emery$Inflor_biomass < 1) ~  muHDI[1,], family = "binomial")
#lines(mu_vals, plogis(coef(zigglm)[1] + coef(zigglm)[2] * mu_vals))
```
