---
title: "tolerance curves plotting"
author: "Silas Tittes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
---

## Data prep
```{r}
source("bayes/load_data.R")
emery <- load_emery()

by(data = emery$treat, INDICES = emery$Species, FUN = function(x) sum(x == max(x)))
by(data = emery$treat, INDICES = emery$Species, FUN = max)
emery$Inflor_biomass[emery$Species == "minor"]
```


```{r}
rstan::traceplot(stanDat, par=c("a"))
rstan::traceplot(stanDat, par=c("b"))
rstan::traceplot(stanDat, par=c("c"))
rstan::traceplot(stanDat, par=c("d"))
rstan::traceplot(stanDat, par=c("e1"))
```


```{r}
library(truncnorm)
library(dplyr)


priorDens <- list(a = NULL, b = NULL, c = NULL, 
                  d = NULL, e1 = NULL, nu = NULL, 
                  beta_0 = NULL, beta_1 = NULL, lp__ = NULL)

nn <- 10000
priorDens$a <- density(rtruncnorm( n = nn, mean = 2, sd = 1, a = 1))
priorDens$b <- density(rtruncnorm( n = nn, mean = 3, sd = 1, a = 1))
priorDens$d <- density(rtruncnorm(nn, mean = min(emery$treat), 
                                  sd = 2, b = min(emery$treat)))
priorDens$e1 <- density(rtruncnorm(nn, mean = max(emery$treat), 
                                  sd = 2, a = max(emery$treat)))
priorDens$nu <- density(rgamma(nn, shape = 20, scale = 0.2))
priorDens$beta_0 <- density(rnorm(nn, 0, 2))
priorDens$beta_1 <- density(rnorm(nn, 0, 2))

priorDens$c <- density(rtruncnorm( n = nn, mean = 0, sd = 10, a = 0))
hyperDens_c <- density(posts$mean_c)

tden <- apply(posts$c, 2, density)
ylimit <- max(sapply(tden, function(x) max(x$y)))
xlimit <- range(sapply(tden, function(x) range(x$x)))
plot(NA,NA, ylim=c(0,ylimit), xlim=xlimit, xlab="", ylab="", main="")
    polygon(priorDens$c, col="red")
    polygon(hyperDens_c, col="blue")
    mtext(text = "c", side = 3)
    lapply(tden, lines)
#!!!!!!
#priorDens$nu <- density(rgamma(nn, shape = 20, scale = 0.2))
#plot(priorDens$nu$x, priorDens$nu$y)
#!!!!!!

par(mfrow=c(5,2))
par(mar=c(3,3,1,1))
namez <- c("a", "b", "c", "mean_c", "d", "e1", "nu", "beta_0", "beta_1", "lp__")
for(i in namez){
  cPost <- posts[[i]]
  if(cPost)
  
  if(length(dim(cPost)) < 2){
    plot(density(cPost), xlab="", ylab="", main="")
    polygon(priorDens[[i]], col="red")
    mtext(text = i, side = 3)
  } else {
    tden <- apply(cPost, 2, density)
    ylimit <- max(sapply(tden, function(x) max(x$y)))
    xlimit <- range(sapply(tden, function(x) range(x$x)))
    plot(NA,NA, ylim=c(0,ylimit), xlim=xlimit, xlab="", ylab="", main="")
    polygon(priorDens[[i]], col="red")
    mtext(text = i, side = 3)
    lapply(tden, lines)
  }
}

tden <- apply(maximadf, 2, density)
ylimit <- max(sapply(tden, function(x) max(x$y)))
xlimit <- range(sapply(tden, function(x) range(x$x)))
plot(NA,NA, ylim=c(0,ylimit), xlim=xlimit, xlab="", ylab="", main="")
mtext(text = "maxima", side = 3)
lapply(tden, lines)

par(opar)
```


```{r}
corrCE <- NULL
for(i in 1:nrow(posts$lp__)){
  cCorr <- cor(posts$c[i,], posts$e1[i,])
  corrCE <- c(corrCE, cCorr)
}
hist(corrCE)
mean(corrCE > 0)
mean(corrCE)
meanz <- summs[,1]
```


curve plots
```{r}

sppMaxVal <- by(data = emery$Inflor_biomass, INDICES = emery$sppint, FUN = max)
names(sppMaxVal) <- unique(emery$Species)

#generate data
xseq <- seq(0,1, length.out=200)
draw_list <- as.list(1:(ndraws*0.05))
sppint_list <- as.list(1:max(emery$sppint))
post_plot_draws <- lapply(sppint_list, function(sp)
            lapply(draw_list, function(pr)
                plot.kumara(xs = xseq,
                            a = posts$a[pr,sp],
                            b = posts$b[pr,sp],
                            #c = posts$c[pr,sp],
                            c = posts$c[pr,sp]/sppMaxVal[sp], #alt
                            d = posts$d[pr,sp],
                            e1 = posts$e1[pr,sp]
                            )
                   )
               )
names(post_plot_draws) <- unique(emery$Species)

paramz <- as.list(c("a", "b", "c", "d", "e1"))
mean_paramz <- lapply(paramz, function(x){
  apply(posts[[x]], 2, mean)
  }
)

names(mean_paramz) <- paramz

mean_plot_draws <- lapply(sppint_list, function(sp)
                plot.kumara(xs = xseq,
                            a = mean_paramz$a[sp],
                            b = mean_paramz$b[sp],
                            #c = mean_paramz$c[sp],
                            c = mean_paramz$c[sp]/sppMaxVal[sp], #alt
                            d = mean_paramz$d[sp],
                            e1 = mean_paramz$e1[sp]
                            )
                   )

names(mean_plot_draws) <- unique(emery$Species)

xr <- range(sapply(post_plot_draws, function(x) x[[1]][[1]]))*1.2
yr <- range(sapply(post_plot_draws, function(x) x[[1]][[2]]))*c(0,1.4)
#yr <- range(sapply(post_plot_draws, function(x) x[[1]][[2]]))*c(0,1.2)
#yr[2] <- ifelse( yr[2] > max(emery$Inflor_biomass), yes = yr[2], max(emery$Inflor_biomass))

#spp_list <- as.list(unique(as.character(emery$Species)))
#lapply(spp_list, function(spp){

#plot data
spp_list <- rev(lasth$tip.label[lasth$edge[,2][lasth$edge[,2] <=
length(lasth$tip.label)]])

#pdf(paste0(getwd(),"/figures/tree_tolerance.pdf"))
pdf("figures/tree_tolerance_scaled.pdf") #alt


c1 <- rep(1, length(spp_list))
c_2_4 <- rep(0, length(spp_list))
c3 <- 2:(length(spp_list)+1)
#possible layouts
#m_lay <- cbind(c1, c1, c_2_4,c3, c_2_4)
m_lay <- cbind(c1, c1, c3, c_2_4)
layout(m_lay)

par(mar=c(0,0,0,0))


plot.phylo(lasth, show.tip.label = F, edge.width = 4, 
           no.margin = T)


for(spp in spp_list){
  #pdf( paste0("figures/", 
              #spp, "_tolerance.pdf"))
  
  plot(NA,NA, xlim=xr, ylim=yr, axes=F, xlab="", ylab="")
  box()
  
  abline(h=seq(yr[1], yr[2], length.out=5), col=alpha("grey80", alpha = 0.5), lwd=2)
  abline(v=seq(xr[1]*0.9, xr[2]*0.9, length.out=5), col=alpha("grey80", alpha = 0.5), lwd=2)
  
  lapply(post_plot_draws[[spp]],
         function(x){
           lines(x[[1]], x[[2]],
                 col=alpha(colour = "black", alpha = 0.05))
           })
  
    lines(mean_plot_draws[[spp]][[1]], 
          mean_plot_draws[[spp]][[2]], 
          col = "white", lwd=2)
    
    
  #legend("topright", paste("L.", spp), bty="n", text.font = 3)
    legend("topleft", spp, bty="n", text.font = 3)
    subEm <- emery[emery$Species == spp, ]
  
  #OPTION 1  
   # points( jitter(subEm$treat), subEm$Inflor_biomass, 
    #       pch=19, col=alpha("grey70", 0.5))
    
  #OPTION 2  
   points(subEm$treat, subEm$Inflor_biomass/sppMaxVal[spp],
         pch=19, col=alpha("grey70", 0.5)) #alt
    
    #dev.off()
}

dev.off()

```


Create posterior draws for the value of the maxima for each species
```{r}
library(parallel)
xseq_big <- seq(0,1, length.out=10000)
draw_list <- as.list(1:(ndraws*1))
sppint_list <- as.list(1:max(emery$sppint))
opt <- mclapply(sppint_list, function(sp){
          sapply(draw_list, function(pr){
            opt.kumara(xs = xseq_big,
                       a = posts$a[pr,sp],
                       b = posts$b[pr,sp],
                       c = posts$c[pr,sp],
                       d = posts$d[pr,sp],
                       e1 = posts$e1[pr,sp]
                       )
            }
          )
  }
)

names(opt) <- unique(emery$Species)
maximadf <- data.frame(opt)
write.table(x = maximadf, file = "bayes/maxima_draws.txt")

mden <- apply(maximadf, 2, density)
ylimit <- max(sapply(mden, function(x) max(x$y)))
xlimit <- range(sapply(mden, function(x) range(x$x)))
plot(NA,NA, xlim=c(0,ylimit), ylim=xlimit, xlab="", ylab="", main="")
sapply(mden, FUN = function(x) lines(x = x$y, y = x$x) )

```



Plotting observed versus predicted
```{r}
meanDraws <- apply(X = posts$mu, 2, mean)

predDF <- data.frame(meanDraws = meanDraws,
                     Inflor_biomass = emery$Inflor_biomass)
predDF_nZero <- predDF[predDF$Inflor_biomass !=0, ]
predDF_Zero <- predDF[predDF$Inflor_biomass == 0, ]

#plot(emery$Inflor_biomass, meanDraws)
#abline(0,1, lty=2, col="red")
plot(predDF_nZero$meanDraws, predDF_nZero$Inflor_biomass - predDF_nZero$meanDraws,
     pch=as.integer(emery$Species))
points(predDF_Zero$meanDraws, predDF_Zero$Inflor_biomass - predDF_Zero$meanDraws,
     pch="z", cex=1.5)
abline(h=0)

smth <- smooth.spline(predDF_nZero$meanDraws, 
                      predDF_nZero$Inflor_biomass - predDF_nZero$meanDraws)
lines(smth$x, smth$y)


```

