---
title: "tolerance curves plotting"
author: "Silas Tittes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    fig_caption: yes
---


```{r, echo=FALSE, results='hide', message=FALSE}

#packages
library(rmarkdown)
library(knitr)
library(formatR)
library(xtable)
library(dplyr)
library(rstan)
library(ggplot2)
library(smoothmest)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())

options(scipen=99) #avoid scientific notation when printing
opts_chunk$set(tidy=TRUE, tidy.opts=list(width.cutoff=70, message=FALSE, results='hide'))
options(bitmapType="cairo")

opar <- par()
opar$cin <- NULL
opar$cra <- NULL
opar$csi <- NULL
opar$cxy <- NULL
opar$din <- NULL
opar$page <- NULL
```


## Data prep
```{r}
setwd("~/Documents/Projects/toleranceCurves/bayes/")
source("tolerance_functions.R")

by(data = emery$treat, INDICES = emery$Species, FUN = function(x) sum(x == max(x)))
by(data = emery$treat, INDICES = emery$Species, FUN = max)
emery$Inflor_biomass[emery$Species == "minor"]
```


```{r}
rstan::traceplot(stanDat, par=c("a"))
rstan::traceplot(stanDat, par=c("b"))
rstan::traceplot(stanDat, par=c("c"))
rstan::traceplot(stanDat, par=c("d"))
rstan::traceplot(stanDat, par=c("e1"))
```



```{r}
library(truncnorm)
library(dplyr)

priorDens <- list(a = NULL, b = NULL, c = NULL, 
                  d = NULL, e1 = NULL, nu = NULL, 
                  beta_0 = NULL, beta_1 = NULL, lp__ = NULL)

nn <- 10000
priorDens$a <- density(rnorm(nn, 2, 2))
priorDens$b <- density(rnorm(nn, 2, 2))
priorDens$c <- density(rnorm(nn, 2, 2))
priorDens$d <- density(rtruncnorm(nn, mean = min(emery$treat), 
                                  sd = 2, b = min(emery$treat)))
priorDens$e1 <- density(rtruncnorm(nn, mean = max(emery$treat), 
                                  sd = 2, a = max(emery$treat)))
priorDens$nu <- density(rgamma(nn, shape = 10, scale = 0.2))
priorDens$beta_0 <- density(rnorm(nn, 0, 2))
priorDens$beta_1 <- density(rnorm(nn, 0, 2))

par(mfrow=c(5,2))
par(mar=c(3,3,1,1))
namez <- c("a", "b", "c", "d", "e1", "nu", "beta_0", "beta_1", "lp__")
for(i in namez){
  cPost <- posts_Normal[[i]]
  if(length(dim(cPost)) < 2){
    plot(density(cPost), xlab="", ylab="", main="")
    polygon(priorDens[[i]], col="red")
    mtext(text = i, side = 3)
  } else {
    tden <- apply(cPost, 2, density)
    ylimit <- max(sapply(tden, function(x) max(x$y)))
    xlimit <- range(sapply(tden, function(x) range(x$x)))
    plot(NA,NA, ylim=c(0,ylimit), xlim=xlimit, xlab="", ylab="", main="")
    polygon(priorDens[[i]], col="red")
    mtext(text = i, side = 3)
    lapply(tden, lines)
  }
}

par(opar)
```


```{r}
corrCE <- NULL
for(i in 1:nrow(posts$lp__)){
  cCorr <- cor(posts$c[i,], posts$e1[i,])
  corrCE <- c(corrCE, cCorr)
}
hist(corrCE)
mean(corrCE > 0)
mean(corrCE)
meanz <- summs[,1]
plot(meanz[grep(pattern = "e1", names(meanz))], meanz[grep(pattern = "^c", names(meanz))])
cor(meanz[grep(pattern = "e1", names(meanz))], meanz[grep(pattern = "^c", names(meanz))])
```

zig plots
```{r}

ndraw <- length(posts$lp__)*0.1

xseq <- seq(0,1, length.out=500)


par(mfrow=c(1,1))
#par(mar=c(3,3,1,1))
#

#xlow <- min(posts$d)
#xhigh <- max(posts$e1+posts$d)
#yrng <- c(0, max(emery$Inflor_biomass))
  
  for(j in 1:max(emery$sppint)){
    
    emery_sub <- subset(emery, sppint == j)
    
    cSpp <- as.character(unique(emery_sub$Species))
    #plot( jitter(emery$treat), emery$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    #plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    
    xlow <- mean(posts$d[,j])
    xhigh <- mean(posts$e1[,j]+posts$d[,j])
    
    #pdf(file = paste0("figures/",cSpp,".pdf"))
    #png(filename = paste0("figures/",cSpp,".png"))
    
    plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, type="n", xlim=c(xlow, xhigh))
  
    for(i in 1:ndraw){
      
      mod.fit <- stretch.kumara(x = xseq, a= posts$a[i,j],# + posts$hyper_a[i],
                                b = posts$b[i,j],# + posts$hyper_b[i],
                                c = posts$c[i,j] # + posts$hyper_c[i]
                                )
      
    
      probZero <- plogis(posts$beta_0[i] + posts$beta_1[i] * mod.fit)
      mod.zig.fit <- (1-probZero)*mod.fit
      #lines with and with zero inflation adjustment
      lines(xseq*posts$e1[i,j] + posts$d[i,j], mod.fit, lwd=1, lty=1, col="blue")
      lines(xseq*posts$e1[i,j] + posts$d[i,j], mod.zig.fit, lwd=1, lty=1)
      }
    
      points( jitter(emery_sub$treat), emery_sub$Inflor_biomass, 
              pch=21, bg="white")
      spln <- smooth.spline(emery_sub$treat, emery_sub$Inflor_biomass)
      lines(spln$x, spln$y, lwd=4, col="red")
      legend("topleft", cSpp, bty="n", cex=1.1)
      
      #dev.off()
  }

par(opar)

```


normal plots
```{r}

ndraw <- length(posts_Normal$lp__)*0.1

xseq <- seq(0,1, length.out=500)

par(mfrow=c(1,1))
#par(mar=c(3,3,1,1))
#
#xlow <- min(posts$d)
#xhigh <- max(posts$e1+posts$d)
#yrng <- c(0, max(emery$Inflor_biomass))
  
  for(j in 1:max(emery$sppint)){
    
    emery_sub <- subset(emery, sppint == j)
    
    cSpp <- as.character(unique(emery_sub$Species))
    #plot( jitter(emery$treat), emery$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    #plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, xlim=c(xlow, xhigh), type="n")
    
    xlow <- mean(posts_Normal$d[,j])
    xhigh <- mean(posts_Normal$e1[,j]+posts_Normal$d[,j])
    
    #pdf(file = paste0("figures/",cSpp,".pdf"))
    #png(filename = paste0("figures/",cSpp,".png"))
    
    plot( jitter(emery_sub$treat), emery_sub$Inflor_biomass, type="n", xlim=c(xlow, xhigh))
  
    for(i in 1:ndraw){
      
      mod.fit <- stretch.kumara(x = xseq, a=posts_Normal$a[i,j],# + posts$hyper_a[i],
                                b = posts_Normal$b[i,j],# + posts$hyper_b[i],
                                c = posts_Normal$c[i,j] # + posts$hyper_c[i]
                                )
      
      #lines with and with zero inflation adjustment
      lines(xseq*posts_Normal$e1[i,j] + posts_Normal$d[i,j], mod.fit, lwd=1, lty=1, col="dodgerblue")
      }
    
      points( jitter(emery_sub$treat), emery_sub$Inflor_biomass, 
              pch=21, bg="white")
      spln <- smooth.spline(emery_sub$treat, emery_sub$Inflor_biomass)
      lines(spln$x, spln$y, lwd=4, col="red")
      legend("topleft", cSpp, bty="n", cex=1.1)
      
      #dev.off()
  }

par(opar)

```


comparing posteriors from normal and gamma zig
```{r}
d <- 4
plot(density(posts$a[,d]))
lines(density(posts_Normal$a[,d]), col="red")

sort(sapply(X = as.list(1:14), function(x) mean(posts$a[,x] > posts_Normal$a[,x])))
sort(sapply(X = as.list(1:14), function(x) mean(posts$b[,x] > posts_Normal$b[,x])))
sort(sapply(X = as.list(1:14), function(x) mean(posts$c[,x] > posts_Normal$c[,x])))
sort(sapply(X = as.list(1:14), function(x) mean(posts$d[,x] > posts_Normal$d[,x])))
sort(sapply(X = as.list(1:14), function(x) mean(posts$e1[,x] > posts_Normal$e1[,x])))

holgym <- list("coulteri", "glabrata", "ferrisiae", "chrysantha")
nameint <- unique(data.frame(emery$Species, emery$sppint))
holgym_int <- sapply(holgym, function(x) which(x == nameint[,1]))

sapply(as.list(holgym_int), 
       function(y) sapply(as.list(holgym_int), 
                          function(x) mean(posts_Normal$d[,x] > posts_Normal$d[,y])
                          )
       )

```


```{r}
plot(sort(posts$a[,14]), sort(posts_Normal$a[,14]))
plot(posts$b[,1], posts_Normal$b[,1])

```


```{r}
# add line for every draw
mu_vals <- seq(min(emery$Inflor_biomass), max(emery$Inflor_biomass), length.out = 1000)

library(scales)
plot(x = NULL, y = NULL, xlim = range(emery$Inflor_biomass), ylim = c(0, 1),
     xlab = "mu", ylab = 'Pr(zero)')
for (i in 1:ndraw) {
  lines(mu_vals, plogis(posts$beta_0[i] + posts$beta_1[i] * mu_vals))
}

```


Create posterior draws for the value of the maxima for each species
```{r}

ndraw <- length(posts$lp__)#*0.01

maxima <- matrix( data = NA, nrow = ndraw, 
                  ncol = length(unique(emery$Species)))
colnames(maxima) <- as.character(unique(emery$Species))

xseq <- seq(0,1, length.out=50000)

for(j in 1:max(emery$sppint)){
  
  emery_sub <- subset(emery, sppint == j)
  
  cSpp <- as.character(unique(emery_sub$Species))

  for(i in 1:ndraw){
    mod.fit <- stretch.kumara(x = xseq, a= posts$a[i,j],# + posts$hyper_a[i],
                              b = posts$b[i,j],# + posts$hyper_b[i],
                              c = posts$c[i,j] # + posts$hyper_c[i]
                              )
    
    probZero <- plogis(posts$beta_0[i] + posts$beta_1[i] * mod.fit)
    mod.zig.fit <- (1-probZero)*mod.fit
    
    #lines with and with zero inflation adjustment
    cTreatSeq <- xseq*posts$e1[i,j] + posts$d[i,j]
    cMaxima <- cTreatSeq[which.max(mod.zig.fit)]
    maxima[i,j] <- cMaxima
  }
  print(paste0(round(100*j/14), "% done."))
}

#write.table(x = maxima, file = "maxima_draws.txt", quote = F, row.names = F, col.names = T)

  mden <- apply(maximadf, 2, density)
  ylimit <- max(sapply(mden, function(x) max(x$y)))
  xlimit <- range(sapply(mden, function(x) range(x$x)))
  plot(NA,NA, xlim=c(0,ylimit), ylim=xlimit, xlab="", ylab="", main="")
  sapply(mden, FUN = function(x) lines(x = x$y, y = x$x) )

  

#library(purrr)
#mtcars %>%
#  split(.$cyl) %>%
#  map(~ lm(mpg ~ wt, data = .)) %>%
#  map(summary) %>%
#  map_dbl("r.squared")


propgt <- function(x){
  cProp <- mean(x > maximadf[,i])
  if(cProp > 0.5){
    return(1 - cProp)
  } else
    return(cProp)
}

for(i in seq_along(unique(emery$Species))){
  print(apply(maximadf, 2, propgt))
}

#split(maximadf,colnames(maximadf))

plot(apply(maximadf, 2, mean), apply(posts$e1, 2, mean))
cor(apply(maximadf, 2, mean), apply(posts$e1, 2, mean))

plot(NA, NA, xlim=range(maximadf), ylim=range(posts$e1))
corr_opt_e1 <- rep(NA, ndraw)
for(i in 1:ndraws){
  points(maximadf[i,], posts$e1[i,], pch=".")
  corr_opt_e1[i] <- cor(maximadf[i,], posts$e1[i,])
}

mean(corr_opt_e1)
hist(corr_opt_e1)
mean(corr_opt_e1 < 0)

for(i in 1:ndraws){
  smooth <- smooth.spline(maximadf[i,], posts$e1[i,])
  lines(smooth$x, smooth$y, col="red", lwd=0.1)
}

sort(by(emery$Species, emery$Species, length))

```


Plotting observed versus predicted for zig
```{r}


meanDraws <- apply(X = posts$mu, 2, mean)
probZero <- plogis( mean(posts$beta_0) + mean(posts$beta_1) * meanDraws)
zigMean <- (1 - probZero) * meanDraws

muZig <- ifelse(test = emery$Inflor_biomass != 0, 
                yes = (1 - plogis(mean(posts$beta_0) + 
                                    mean(posts$beta_1) * meanDraws))
                                    * meanDraws, 
                no = plogis(mean(posts$beta_0) + mean(posts$beta_1) * meanDraws))

plot(emery$Inflor_biomass, muZig)
abline(0,1, lty=2, col="red")
plot(muZig, emery$Inflor_biomass - muZig)
abline(h=0,lty=2, col="red")
```



```{r}
xseq <- c(0,1)
rangez <- array(data = NA, dim = c(ncol(posts$a), 2))
for(j in 1:ncol(posts$a)){
  rangez[j,] <- c(max(posts$d[,j]), min(posts$e1[,j] + posts$d[,j]))  
}

c(max(rangez[,1]), min(rangez[,2]))
 
```
